# week08/k8s/frontend.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend               # match your existing deployment name
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: acr-pull-secret   # ensure ACR pulls work
      containers:
        - name: frontend-container  # match your existing container name
          image: sarah7p28acr.azurecr.io/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # FYI: env below are not used by a static Nginx site; safe to remove.
          # env:
          #   - name: PRODUCT_API_URL
          #     value: "http://4.195.18.94:8000"
          #   - name: ORDER_API_URL
          #     value: "http://20.227.109.201:8001"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-w08e1          # keep existing service name you’re using
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
