name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'
  workflow_dispatch:

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} \
             -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest ./frontend
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest
